services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes: 
      - mongo_container:/data/db
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    env_file:
      - .env
    links:
      - mongodb
    networks:
      - mongo_network
    restart: no
    depends_on:
      - mongodb

volumes:
  mongo_container:

networks:
  mongo_network:
    driver: bridge